export const lista = [
    {nome: 'Caio Reis',sexo: 'M',idade: 18},
    {nome: 'Arthur Mendes',sexo: 'M',idade: 16},
    {nome: 'Leticia Maria',sexo: 'F',idade: 17},
    {nome: 'Sofia Mendes Costa',sexo: 'F',idade: 8},
    {nome: 'Leonardo Mendes',sexo: 'M',idade: 6},
    {nome: 'Luciane Costa',sexo: 'F',idade: 46},
    {nome: 'Josiane Andrade',sexo: 'F',idade: 72},
    {nome: 'Gerson Mendes',sexo: 'M',idade: 85},
    {nome: 'Claudia Alves Andrade',sexo: 'F',idade: 25},
    {nome: 'Josimara Gomes',sexo: 'F',idade: 37},
    {nome: 'Lais Lima',sexo: 'F',idade: 93},
    {nome: 'Maria Joaquina',sexo: 'F',idade: 53},
    {nome: 'Joao Victor Silva',sexo: 'M',idade: 13},
    {nome: 'Luan George',sexo: 'M',idade: 22},
    {nome: 'Felipe Carvalho',sexo: 'M',idade: 61},
    {nome: 'Beatriz Ferreira',sexo: 'F',idade: 1},
    {nome: 'Ricardo ',sexo: 'M',idade: 15},
    {nome: 'Gabriela',sexo: 'F',idade: 18},
    {nome: 'Milena Batista',sexo: 'F',idade: 3},
    {nome: 'Henrique Mark',sexo: 'M',idade: 30},
    {nome: 'Livia Carvalho',sexo: 'F',idade: 50},
    {nome: 'Gabriel Jake',sexo: 'M',idade: 60},
    {nome: 'Vinicios Alves',sexo: 'M',idade: 113},
    {nome: 'Vitoria Alves',sexo: 'F',idade: 100},
    {nome: 'Theo Andrade',sexo: 'M',idade: 3},
    {nome: 'Miguel Batista',sexo: 'M',idade: 24},
    {nome: 'Giovanna Ferreira',sexo: 'F',idade: 82},
    {nome: 'Daniel Silva',sexo: 'M',idade: 28},
    {nome: 'Eduardo Castro',sexo: 'M',idade: 86},
    {nome: 'Eduardo Pereira',sexo: 'M',idade: 86},
    {nome: 'Linda McCartney',sexo: 'F',idade: 16},
    {nome: 'Melissa Silva',sexo: 'F',idade: 114},
    {nome: 'Laura McCartney',sexo: 'F',idade: 32},
    {nome: 'George Melo',sexo: 'M',idade: 37},
]

